---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyr)
library(dplyr)
library(ggplot2)
```



```{r}
food_consumption <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv')
```

```{r}
head(food_consumption)
unique(food_consumption$food_category)
```


```{r}
grouped_summaries<-food_consumption %>% group_by(country) %>% summarize(sum_co2=sum(co2_emmission))
head(grouped_summaries)
```

```{r}
top<-grouped_summaries %>% top_n(5,wt = sum_co2)
top
```




Data summaraization 

```{r}
summary.long<-food_consumption %>% group_by(food_category,country) %>% summarize(sum.CO2=sum(co2_emmission))
summary.long.top<-summary.long[summary.long$country %in% top$country,]
```

```{r}
head(summary.long.top)
```

sort food categories by decreasing values
```{r}
foods<-as.vector(unique(summary.long.top[order(summary.long.top$sum.CO2,decreasing = T), "food_category"]))
summary.long.top$food_category<-factor(summary.long.top$food_category, ordered=T, levels =foods$food_category)
```
sort countries by decreasing order of top emitting countries

```{r}
top_cs<-as.vector(top[order(top$sum_co2,decreasing = T), "country"])
summary.long.top$country<-factor(summary.long.top$country, ordered=T, levels =top_cs$country)
```

```{r}
ggplot(summary.long.top, aes(x=country, y=sum.CO2)) + 
  geom_bar(stat='identity') + facet_wrap(~food_category) + theme(axis.text.x = element_text(angle=45,hjust=1)) + theme_bw() + theme(axis.text.x = element_text(angle=45, hjust=1)) + ylab(expression(paste('total ',CO['2'],' emissions (Kg ',person^-1, year^-1,')',sep=' '))) + xlab('Top Emmitting Countries')
ggsave('food consumption.pdf')
```

